apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: entro-kibana
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: entro-elastic
  http:
    service:
      spec:
        type: LoadBalancer
